FROM scratch
#COPY hello /
#RUN /bin/sh touch 1.txt
RUN env
#CMD env
#RUN bin/sh -c 'echo hello world > 1.txt'
#CMD ["/bin/sh", "cat 1.txt"]


#https://github.com/tianon/dockerfiles/blob/master/true/Dockerfile
