FROM busybox
#COPY hello /
#RUN /bin/sh touch 1.txt

#CMD env
#RUN bin/sh -c 'echo hello world > 1.txt'
#CMD ["/bin/sh", "cat 1.txt"]

RUN sudo echo hi
#https://github.com/tianon/dockerfiles/blob/master/true/Dockerfile
